manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: refil
      url-base: https://github.com/refil
  projects:
    - name: zmk
      remote: refil
      revision: 86114880a03d3e219a1fa534d7c98d4786b1dfac
      import: app/west.yml
  self:
    path: config
